name: 'Cleanup Pull Request'
on:
  pull_request_target:
    types: [closed]

jobs:
  cleanup-pr:
    name: 'Cleanup Pull Request'
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Kubernetes Login
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Delete Helm Chart
        run: helm delete pr-${{ github.event.pull_request.number }} --namespace kubernetes-pr-testing
