name: 'Cleanup Pull Request'
on:
  pull_request_target:
    types: [closed]

jobs:
  cleanup-pr:
    name: 'Cleanup Pull Request'
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Kubernetes Login
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Delete Helm Chart
        run: helm delete pr-${{ github.event.pull_request.number }} --namespace kubernetes-pr-testing

      - name: Remove Docker Image
        run: |
          TOKEN=`curl -s -H "Content-Type: application/json" -X POST -H "Content-Type: application/json" -d '{"username":"${{ secrets.DOCKERHUB_USERNAME }}", "password":"${{ secrets.DOCKERHUB_TOKEN }}"}' "https://hub.docker.com/v2/users/login/" | jq -r .token`
          curl -X DELETE -H "Authorization: JWT ${TOKEN}" "https://hub.docker.com/v2/repositories/glenndehaan/kubernetes-pr-testing/tags/pr-${{ github.event.pull_request.number }}/"
