name: 'Deploy Pull Request'
on:
  pull_request_target:
    types: [opened]

jobs:
  deploy-pr:
    name: 'Deploy Pull Request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: glenndehaan/kubernetes-pr-testing:pr-${{ github.event.pull_request.number }}

      - name: Kubernetes Login
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Install Helm Chart
        working-directory: _scripts/helm
        run: |
          helm upgrade pr-${{ github.event.pull_request.number }} kubernetes-pr-testing \
            --install \
            --namespace kubernetes-pr-testing \
            --create-namespace \
            --wait \
            --set image.tag=pr-${{ github.event.pull_request.number }} \
            --set ingress.hosts[0].host=kubernetes-pr-testing-${{ github.event.pull_request.number }}.kube.devone.nl,ingress.hosts[0].paths[0].path=/,ingress.hosts[0].paths[0].pathType=Prefix \
            --set ingress.tls[0].secretName=kubernetes-pr-testing-${{ github.event.pull_request.number }}-kube-devone-nl-tls \
            --set ingress.tls[0].hosts[0]=kubernetes-pr-testing-${{ github.event.pull_request.number }}.kube.devone.nl

      - name: Post comment to Pull Request
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: Your Pull Request Deployment is ready for review at https://kubernetes-pr-testing-${{ github.event.pull_request.number }}.kube.devone.nl
